name: Run cdn
on: push
jobs:
    runCdn:
        name: Run cdn workflow
        runs-on: ubuntu-22.04
        steps:
            - name: Trigger workflow dispatch
              run: |
                  curl \
                  -X POST \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/ehanahamed/cdn/actions/workflows/cdn.yml/dispatches \
                  -d '{"ref":"main","inputs":{"repo":"ehanahamed/productivecss"}}'
